apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - /data/minio/
            - --console-address
            - :9001
          env:
            - name: MINIO_ROOT_PASSWORD
              value: '!ChangeMe!'
            - name: MINIO_ROOT_USER
              value: minio
          image: minio/minio:latest
          name: minio
          resources: {}
      restartPolicy: Always
status: {}
