apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "deployment-{{ .Values.name }}-{{ .Values.auth.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "etandem.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "etandem.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          args:
            - start-dev
          ports:
            - name: direct
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.auth.env.keycloackAdmin }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "{{ .Values.auth.env.keycloackAdminPassword }}"
            - name: KC_DB
              value: "{{ .Values.auth.env.kcDB }}"
            - name: KC_DB_USERNAME
              value: "{{ .Values.auth.env.kcDBUsername }}"
            - name: KC_DB_PASSWORD
              value: "{{ .Values.auth.env.kcDBPassword }}"
            - name: KC_DB_URL
              value: "jdbc:postgresql://database:5432/{{ .Values.postgresDB }}"
            - name: KC_DB_SCHEMA
              value: "{{ .Values.auth.env.kcDBSchema }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
