{{- if .Values.database.ingress.enabled -}}
{{- $svcPort := .Values.database.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ .Values.name }}-{{ .Values.database.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
  {{- with .Values.database.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.database.ingress.tls }}
  tls:
    {{- range .Values.database.ingress.tls }}
    - hosts:
        {{- range .hosts }}        
        {{ $fqdn := printf "%s.%s" . $.Values.domain -}}
        - {{ $fqdn }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.database.ingress.hosts }}
    {{ $fqdn := printf "%s.%s" .host $.Values.domain -}}
    - host: {{ $fqdn }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . | quote}}
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Values.name }}-{{ $.Values.database.name }}"
                port:
                  number: {{ $svcPort }}
          {{- end }}
      {{- end }}
{{- end }}
