apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-{{ .Values.database.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: direct
      protocol: TCP
      name: direct
  selector:
    {{- include "etandem.selectorLabels" . | nindent 4 }}
