apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-{{ .Values.minio.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9001
      targetPort: direct
      protocol: TCP
      name: direct
  selector:
    {{- include "etandem.selectorLabels" . | nindent 4 }}
