apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem.fullname" . }}-{{ .Values.auth.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.auth.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.auth.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          args:
            - start-dev
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/ready
              port: admin
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /health/ready
              port: admin
            periodSeconds: 30
            initialDelaySeconds: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.auth.env.keycloackAdmin }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "{{ .Values.auth.env.keycloackAdminPassword }}"
            - name: KC_DB
              value: "{{ .Values.auth.env.kcDB }}"
            - name: KC_DB_USERNAME
              value: "{{ .Values.postgresUser }}"
            - name: KC_DB_PASSWORD
              value: "{{ .Values.postgresPassword }}"
            - name: KC_DB_URL
              value: "jdbc:postgresql://etandem-database:5432/{{ .Values.postgresDB }}"
            - name: KC_DB_SCHEMA
              value: "{{ .Values.auth.env.kcDBSchema }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
