#
#   Copyright ou © ou Copr. Université de Lorraine, (2025)
#
#   Direction du Numérique de l'Université de Lorraine - SIED
#
#   Ce logiciel est un programme informatique servant à rendre accessible
#   sur mobile et sur internet l'application ULEP (University Language
#   Exchange Programme) aux étudiants et aux personnels des universités
#   parties prenantes.
#
#   Ce logiciel est régi par la licence CeCILL 2.1, soumise au droit français
#   et respectant les principes de diffusion des logiciels libres. Vous pouvez
#   utiliser, modifier et/ou redistribuer ce programme sous les conditions
#   de la licence CeCILL telle que diffusée par le CEA, le CNRS et INRIA
#   sur le site "http://cecill.info".
#
#   En contrepartie de l'accessibilité au code source et des droits de copie,
#   de modification et de redistribution accordés par cette licence, il n'est
#   offert aux utilisateurs qu'une garantie limitée. Pour les mêmes raisons,
#   seule une responsabilité restreinte pèse sur l'auteur du programme, le
#   titulaire des droits patrimoniaux et les concédants successifs.
#
#   À cet égard, l'attention de l'utilisateur est attirée sur les risques
#   associés au chargement, à l'utilisation, à la modification et/ou au
#   développement et à la reproduction du logiciel par l'utilisateur étant
#   donné sa spécificité de logiciel libre, qui peut le rendre complexe à
#   manipuler et qui le réserve donc à des développeurs et des professionnels
#   avertis possédant des connaissances informatiques approfondies. Les
#   utilisateurs sont donc invités à charger et à tester l'adéquation du
#   logiciel à leurs besoins dans des conditions permettant d'assurer la
#   sécurité de leurs systèmes et/ou de leurs données et, plus généralement,
#   à l'utiliser et à l'exploiter dans les mêmes conditions de sécurité.
#
#   Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
#   pris connaissance de la licence CeCILL 2.1, et que vous en avez accepté les
#   termes.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem.fullname" . }}-{{ .Values.auth.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.auth.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.auth.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-database
          image: actions/pg_isready
          command: ["/bin/bash","-c"]
          args: ["set -x; while [ $(pg_isready -d $DB_NAME -h $HOST_NAME -p 5432 -U $DB_USER -q; echo $?) -ne 0 ]; do sleep 5; done"]          
          env:
            - name: DB_NAME
              value: "{{ .Values.postgresql.global.postgresql.auth.database }}"
            - name: HOST_NAME
              value: "{{ include "etandem.name" . }}-postgresql.{{ .Release.Namespace }}"
            - name: DB_USER
              value: "{{ .Values.postgresql.global.postgresql.auth.username }}"
        - name: mount-custom-theme
          image: "{{ .Values.auth.initImage.repository }}:{{ .Values.auth.initImage.tag}}"
          volumeMounts:
            - name: "{{ .Values.auth.name }}-themes"
              mountPath: /auth-themes
          command: [/bin/sh, -c]
          args:
            - |
              echo "Copying themes..."
              cp -R /app/themes/* /auth-themes
              echo "All themes copied"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          args:
            - start
            - --proxy-headers 
            - xforwarded            
            - --health-enabled
            - 'true'
            - --hostname
            - "{{ .Values.keycloakUrl }}.{{ .Values.domain }}"
            - --import-realm
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: admin
              containerPort: 9990
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.auth.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.auth.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.auth.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.auth.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.auth.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.auth.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.auth.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.auth.env.keycloakAdmin }}"
            - name: KC_DB
              value: "{{ .Values.auth.env.kcDB }}"
            - name: KC_DB_USERNAME
              value: "{{ .Values.postgresql.global.postgresql.auth.username }}"
            - name: KC_DB_URL
              value: "jdbc:postgresql://{{ .Values.name }}-postgresql.{{ .Release.Namespace }}:5432/{{ .Values.postgresql.global.postgresql.auth.database }}"
            - name: KC_DB_SCHEMA
              value: "{{ .Values.auth.env.kcDBSchema }}"
            - name: PROXY_ADDRESS_FORWARDING
              value: "{{ .Values.auth.env.proxyAddressForwarding }}"
            - name: KEYCLOAK_HOSTNAME
              value: "{{ .Values.keycloakUrl }}.{{ .Values.domain }}"
            - name: KC_LOG_LEVEL
              value: "{{ .Values.auth.env.logLevel }}"
            - name: KC_PROXY
              value: "edge"
          envFrom: 
            - secretRef: 
                name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.auth.name }}"
          volumeMounts:
          - name: "{{ .Values.auth.name }}-realm"
            mountPath: /opt/keycloak/data/import
          - name: "{{ .Values.auth.name }}-themes"
            mountPath: /opt/keycloak/themes
      volumes:
      - name: "{{ .Values.auth.name }}-realm"
        configMap:
          name: "{{ include "etandem.name" . }}-realm-{{ .Values.auth.name }}"
      - name: "{{ .Values.auth.name }}-themes"
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
