apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.auth.name }}"
type: Opaque
stringData:
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.auth.env.keycloackAdminPassword }}
  KC_DB_PASSWORD: {{ .Values.global.postgresql.auth.password }}