apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.auth.name }}"
type: Opaque
data:
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.auth.env.keycloackAdminPassword | b64enc | quote }}
  KC_DB_PASSWORD: {{ .Values.global.postgresql.password | b64enc | quote }}