apiVersion: v1
kind: Service
metadata:
  name: "{{ include "etandem.fullname" . }}-{{ .Values.auth.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # - port: 8080
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    - port: 9990
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.auth.name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
