apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret-{{ .Values.git.name }}"
type: Opaque
stringData:
  GIT_PASSWORD: {{ .Values.git.env.gitPassword }}
  MINIO_SECRET_KEY: {{ .Values.git.env.minioSecretKey }}
