apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postinstall-configmap
data:
  inject.sh: |-
{{ .Files.Get "default_data/inject.sh" | indent 4}}
  projects.json: |-
{{ .Files.Get "default_data/projects.json" | indent 4}}
  components.json: |-
{{ .Files.Get "default_data/components.json" | indent 4}}