#
#   Copyright ou © ou Copr. Université de Lorraine, (2025)
#
#   Direction du Numérique de l'Université de Lorraine - SIED
#
#   Ce logiciel est un programme informatique servant à rendre accessible
#   sur mobile et sur internet l'application ULEP (University Language
#   Exchange Programme) aux étudiants et aux personnels des universités
#   parties prenantes.
#
#   Ce logiciel est régi par la licence CeCILL 2.1, soumise au droit français
#   et respectant les principes de diffusion des logiciels libres. Vous pouvez
#   utiliser, modifier et/ou redistribuer ce programme sous les conditions
#   de la licence CeCILL telle que diffusée par le CEA, le CNRS et INRIA
#   sur le site "http://cecill.info".
#
#   En contrepartie de l'accessibilité au code source et des droits de copie,
#   de modification et de redistribution accordés par cette licence, il n'est
#   offert aux utilisateurs qu'une garantie limitée. Pour les mêmes raisons,
#   seule une responsabilité restreinte pèse sur l'auteur du programme, le
#   titulaire des droits patrimoniaux et les concédants successifs.
#
#   À cet égard, l'attention de l'utilisateur est attirée sur les risques
#   associés au chargement, à l'utilisation, à la modification et/ou au
#   développement et à la reproduction du logiciel par l'utilisateur étant
#   donné sa spécificité de logiciel libre, qui peut le rendre complexe à
#   manipuler et qui le réserve donc à des développeurs et des professionnels
#   avertis possédant des connaissances informatiques approfondies. Les
#   utilisateurs sont donc invités à charger et à tester l'adéquation du
#   logiciel à leurs besoins dans des conditions permettant d'assurer la
#   sécurité de leurs systèmes et/ou de leurs données et, plus généralement,
#   à l'utiliser et à l'exploiter dans les mêmes conditions de sécurité.
#
#   Le fait que vous puissiez accéder à cet en-tête signifie que vous avez
#   pris connaissance de la licence CeCILL 2.1, et que vous en avez accepté les
#   termes.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ .Values.name }}-{{ .Values.weblate.name }}"
  labels:
    {{- include "ulep-weblate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.weblate.autoscaling.enabled }}
  replicas: {{ .Values.weblate.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.name }}-{{ .Values.weblate.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ .Values.name }}-{{ .Values.weblate.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ulep-weblate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /app/data"]
          volumeMounts:
          - name: "{{ .Values.weblate.name }}-data"
            mountPath: /app/data          
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.weblate.image.repository }}:{{ .Values.weblate.image.tag }}"
          imagePullPolicy: {{ .Values.weblate.image.pullPolicy }}          
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /minio/health/live
          #     port: https
          #   initialDelaySeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /minio/health/live
          #     port: https
          #   initialDelaySeconds: 30
          #   periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: WEBLATE_SITE_DOMAIN
              value: "{{ .Values.weblate.env.site }}.{{ .Values.domain }}"
            - name: WEBLATE_ENABLE_HTTPS
              value: "true"
            - name: WEBLATE_EMAIL_HOST
              value: "{{ .Values.weblate.env.emailHost }}"
            - name: WEBLATE_EMAIL_PORT
              value: "{{ .Values.weblate.env.emailPort }}"
            - name: WEBLATE_ALLOWED_HOSTS
              value: "{{ .Values.weblate.env.allowedHost }}"
            - name: WEBLATE_SERVER_EMAIL
              value: "{{ .Values.weblate.env.serverEmail }}"
            - name: WEBLATE_DEFAULT_FROM_EMAIL
              value: "{{ .Values.weblate.env.serverEmail }}"
            - name: WEBLATE_ADMIN_EMAIL
              value: "{{ .Values.weblate.env.adminEmail }}"
            - name: POSTGRES_DATABASE
              value: "{{ .Values.global.postgresql.auth.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.global.postgresql.auth.username }}"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_HOST
              value: "{{ .Values.name }}-postgresql.{{ .Release.Namespace }}"
            - name: REDIS_HOST
              value: "{{ .Values.name }}-redis-master.{{ .Release.Namespace }}"
            - name: WEBLATE_REGISTRATION_OPEN
              value: "0"
            - name: MINIO_HOST
              value: "{{ .Values.git.env.minioHost }}"
            - name: MINIO_ACCESS_KEY
              value: "{{ .Values.git.env.minioAccessKey }}"
          envFrom: 
            - secretRef: 
                name: "{{ .Values.name }}-secret-{{ .Values.weblate.name }}"
          volumeMounts:
          - name: "{{ .Values.weblate.name }}-data"
            mountPath: /app/data          
      volumes:
      - name: "{{ .Values.weblate.name }}-data"
        persistentVolumeClaim:
          claimName:  "{{ .Values.name }}-pvc-{{ .Values.weblate.name }}"      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
