apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name }}-pvc-{{ .Values.weblate.name }}"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  # volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.weblate.pv.storage }}"
  storageClassName: "{{ .Values.weblate.pv.storageClassName }}"