apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret-{{ .Values.weblate.name }}"
type: Opaque
data:
  WEBLATE_ADMIN_PASSWORD: {{ .Values.weblate.env.adminPassword | b64enc | quote }}
  WEBLATE_EMAIL_HOST_USER: {{ .Values.weblate.env.emailHostUser | b64enc | quote }}
  WEBLATE_EMAIL_HOST_PASSWORD: {{ .Values.weblate.env.emailHostPassword | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.postgresPassword | b64enc | quote }}
  