apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-secret-{{ .Values.weblate.name }}"
type: Opaque
stringData:
  WEBLATE_ADMIN_PASSWORD: {{ .Values.weblate.env.adminPassword }}
  WEBLATE_EMAIL_HOST_USER: {{ .Values.weblate.env.emailHostUser }}
  WEBLATE_EMAIL_HOST_PASSWORD: {{ .Values.weblate.env.emailHostPassword }}
  POSTGRES_PASSWORD: {{ .Values.global.postgresql.auth.password }}
  REDIS_PASSWORD: {{ .Values.global.redis.password }}