apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-{{ .Values.weblate.name }}"
  labels:
    {{- include "ulep-weblate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.weblate.service.type }}
  ports:
    - port: {{ .Values.weblate.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ .Values.name }}-{{ .Values.weblate.name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
