apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem.fullname" . }}-{{ .Values.admin.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.admin.autoscaling.enabled }}
  replicas: {{ .Values.admin.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.admin.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.admin.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - rm -rf /srv/app/build/env/;
              mkdir -p /srv/app/build/env/;
              cp /tmp/env/config.js /srv/app/build/env/;
              cd /srv/app; serve -s build -l 80;          
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.admin.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.admin.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.admin.probes.startup.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.admin.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.admin.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.admin.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: {{ .Values.admin.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.admin.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.admin.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: REACT_APP_API_URL
              value: "https://{{ .Values.apiUrl }}.{{ .Values.domain }}"
            - name: REACT_APP_SENTRY_DSN
              value: "{{ .Values.admin.env.sentryDsn }}"
            - name: REACT_APP_JITSI_DOMAIN
              value: "{{ .Values.jitsiUrl }}.{{ .Values.domain }}"
            - name: REACT_APP_CHAT_URL
              value: "https://{{ .Values.chatUrl }}.{{ .Values.domain }}"
            - name: REACT_APP_SOCKET_CHAT_URL
              value: "https://{{ .Values.socketChatUrl }}.{{ .Values.domain }}"
            - name: REACT_APP_DEFAULT_TRANSLATION_LANGUAGE
              value: "{{ .Values.api.env.defaultTranslationLanguage }}"
            - name: REACT_APP_LIMITED_FEATURES
              value: "{{ .Values.limitedFeatures }}"
          volumeMounts:
          - name: "{{ .Values.admin.name }}-env"
            mountPath: /tmp/env/
      volumes:
      - name: "{{ .Values.admin.name }}-env"
        configMap:
          name: "{{ .Values.name }}-env-admin-{{ .Values.admin.name }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
