apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.admin.name }}"
type: Opaque
data:
  REACT_APP_KEYCLOAK_CLIENT_SECRET: {{ .Values.admin.env.keycloakClientSecret | b64enc | quote }}