apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.name }}"
spec:
  dnsNames:
    - "{{ .Values.api.name }}.{{ .Values.domain }}"
    - "{{ .Values.minio.name }}.{{ .Values.domain }}"
    - "{{ .Values.admin.name }}.{{ .Values.domain }}"
    - "{{ .Values.auth.name }}.{{ .Values.domain }}"
    - "{{ .Values.webapp.name }}.{{ .Values.domain }}"
  issuerRef:
    name: "{{ .Values.issuerName }}"
    kind: ClusterIssuer
  secretName: "{{ .Values.name }}-tls"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
