apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ .Values.name }}'
spec:
  dnsNames:
    - '{{ .Values.apiUrl }}.{{ .Values.domain }}'
    - '{{ .Values.minioUrl }}.{{ .Values.domain }}'
    - '{{ .Values.minioApiUrl }}.{{ .Values.domain }}'
    - '{{ .Values.adminUrl }}.{{ .Values.domain }}'
    - '{{ .Values.keycloakUrl }}.{{ .Values.domain }}'
    - '{{ .Values.webappUrl }}.{{ .Values.domain }}'
    - '{{ .Values.chatUrl }}.{{ .Values.domain }}'
    - '{{ .Values.socketChatUrl }}.{{ .Values.domain }}'
  issuerRef:
    name: '{{ .Values.issuerName }}'
    kind: ClusterIssuer
  secretName: '{{ .Values.name }}-tls'
