apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "wildcard-{{ .Values.name }}-tls"
spec:
  dnsNames:
  - "*.{{ .Values.domain }}"
  issuerRef:
    name: {{ .Values.issuerName }}
    kind: ClusterIssuer
  secretName: "wildcard-{{ .Values.name }}-tls"