{{- if gt (len .Values.imagePullSecrets) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkicmVnaXN0cnkuZ2l0bGFiLmNvbSI6IHt9LAoJCSJyZy5mci1wYXIuc2N3LmNsb3VkIjogewoJCQkiYXV0aCI6ICJibTlzYjJkcGJqcGxOVE00WkdOall5MDFNV1EyTFRReE0yRXRZakExT0MwME1EWmhabVkxWVRnNU1XVT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
{{- end }}