apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem.fullname" . }}-{{ .Values.api.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.api.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.api.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-database-and-migrate
        image: "{{ .Values.api.initImage.repository }}:{{ .Values.api.initImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.initImage.pullPolicy }}
        env:
          - name: DB_NAME
            value: "{{ .Values.global.postgresql.auth.database }}"
          - name: HOST_NAME
            value: "{{ include "etandem.name" . }}-postgresql.{{ .Release.Namespace }}"
          - name: DB_USER
            value: "{{ .Values.global.postgresql.auth.username }}"
          - name: DATABASE_URL
            value: "postgresql://{{ .Values.global.postgresql.auth.username }}:$(PGPASSWORD)@{{ include "etandem.name" . }}-postgresql.{{ .Release.Namespace }}:5432/{{ .Values.global.postgresql.auth.database }}?schema=public"
        envFrom: 
          - secretRef: 
              name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: direct
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ADMIN_URL
              value: "https://{{ .Values.adminUrl }}.{{ .Values.domain }}"
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.global.postgresql.auth.username }}:$(PGPASSWORD)@{{ include "etandem.name" . }}-postgresql.{{ .Release.Namespace }}:5432/{{ .Values.global.postgresql.auth.database }}?schema=public"
            - name: KEYCLOAK_BASE_URL
              value: "https://{{ .Values.keycloakUrl }}.{{ .Values.domain }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.api.env.keycloakRealm }}"
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.api.env.keycloakAdmin }}"
            - name: KEYCLOAK_CLIENT_ID
              value: "{{ .Values.api.env.keycloakClientId }}"
            - name: MINIO_URL
              value: "{{ .Values.minioApiUrl }}.{{ .Values.domain }}"
            - name: MINIO_PUBLIC_URL
              value: "https://{{ .Values.minioApiUrl }}.{{ .Values.domain }}"
            - name: MINIO_USE_SSL
              value: "true"
            - name: SMTP_HOST
              value: "{{ .Values.api.env.smtpHost }}"
            - name: SMTP_PORT
              value: "{{ .Values.api.env.smtpPort }}"
            - name: SMTP_SECURE
              value: "{{ .Values.api.env.smtpSecure }}"
            - name: SMTP_SENDER
              value: "{{ .Values.api.env.smtpSender }}"
            - name: SMTP_DISABLE_BOOT_VERIFICATION
              value: "{{ .Values.api.env.smtpDisableBootVerification }}"
            - name: LOG_LEVEL
              value: "{{ .Values.api.env.logLevel }}"
            - name: LOG_LEVEL
              value: "{{ .Values.api.env.logLevel }}"
            - name: EMAIL_TRANSLATIONS_ENDPOINT
              value: "{{ .Values.api.env.emailsTranslationsEndpoint }}"
            - name: EMAIL_TRANSLATIONS_COMPONENT
              value: "{{ .Values.api.env.emailsTranslationsComponent }}"
            - name: EMAIL_ASSETS_ENDPOINT
              value: "{{ .Values.api.env.emailsAssetsEndpoint }}"
            - name: EMAIL_ASSETS_BUCKET
              value: "{{ .Values.api.env.emailsAssetsBucket }}"
            - name: APP_LINK_APPLE_STORE
              value: "{{ .Values.api.env.appLinkAppleStore }}"
            - name: APP_LINK_PLAY_STORE
              value: "{{ .Values.api.env.appLinkPlayStore }}"
            - name: TRANSLATIONS_ENDPOINT
              value: "{{ .Values.api.env.translationsEndpoint }}"
            - name: TRANSLATIONS_ENDPOINT_SUFFIX
              value: "{{ .Values.api.env.translationsEndpointSuffix }}"
          envFrom:
            - secretRef: 
                name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
