apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem.fullname" . }}-{{ .Values.api.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.api.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.api.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: wait-for-database-and-migrate
        image: "{{ .Values.api.initImage.repository }}:{{ .Values.api.initImage.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.initImage.pullPolicy }}
        env:
          - name: DB_NAME
            value: "{{ .Values.global.postgresql.auth.database }}"
          - name: HOST_NAME
            value: "{{ include "etandem.name" . }}-postgresql.{{ .Release.Namespace }}"
          - name: DB_USER
            value: "{{ .Values.global.postgresql.auth.username }}"
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: database-url
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: direct
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: {{ .Values.api.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.readiness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: {{ .Values.api.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.probes.liveness.periodSeconds }}
            failureThreshold: {{ .Values.api.probes.liveness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ADMIN_URL
              value: "https://{{ .Values.adminUrl }}.{{ .Values.domain }}"
            - name: APP_URL
              value: "https://{{ .Values.api.env.appUrl }}.{{ .Values.domain }}"
            - name: LOG_LEVEL
              value: "{{ .Values.api.env.logLevel }}"
            - name: DEFAULT_TRANSLATION_LANGUAGE
              value: "{{ .Values.api.env.defaultTranslationLanguage }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: database-url
            - name: KEYCLOAK_BASE_URL
              value: "https://{{ .Values.keycloakUrl }}.{{ .Values.domain }}"
            - name: KEYCLOAK_REALM
              value: "{{ .Values.api.env.keycloakRealm }}"
            - name: KEYCLOAK_ADMIN
              value: "{{ .Values.api.env.keycloakAdmin }}"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: keycloak-admin-password
            - name: KEYCLOAK_CLIENT_ID
              value: "{{ .Values.api.env.keycloakClientId }}"
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: keycloak-client-secret
            - name: KEYCLOAK_ADMIN_GROUP_ID
              value: "{{ .Values.api.env.keycloakAdminGroupId }}"
            - name: MINIO_HOST
              value: "{{ .Values.api.env.minioHost }}.{{ .Values.domain }}"
            - name: MINIO_PORT
              value: "{{ .Values.api.env.minioPort }}"
            - name: MINIO_USE_SSL
              value: "{{ .Values.api.env.minioUseSsl }}"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: minio-secret-key
            - name: TRANSLATIONS_ENDPOINT
              value: "{{ .Values.api.env.translationsEndpoint }}"
            - name: TRANSLATIONS_ENDPOINT_SUFFIX
              value: "{{ .Values.api.env.translationsEndpointSuffix }}"
            - name: TRANSLATIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.api.name }}"
                  key: translations-token
            - name: CONNECTOR_URL
              value: "{{ .Values.api.env.connectorUrl }}"
            - name: CONNECTOR_TOKEN
              value: "{{ .Values.api.env.connectorToken }}"
            - name: EMAIL_ASSETS_BUCKET
              value: "{{ .Values.api.env.emailsAssetsBucket }}"
            - name: EMAIL_TRANSLATIONS_COMPONENT
              value: "{{ .Values.api.env.emailsTranslationsComponent }}"
            - name: EMAIL_ASSETS_PUBLIC_ENDPOINT
              value: "https://{{ .Values.api.env.emailsAssetsPublicEndpoint }}.{{ .Values.domain }}"
            - name: APP_LINK_APPLE_STORE
              value: "{{ .Values.api.env.appLinkAppleStore }}"
            - name: APP_LINK_PLAY_STORE
              value: "{{ .Values.api.env.appLinkPlayStore }}"
            - name: SMTP_DISABLE_BOOT_VERIFICATION
              value: "{{ .Values.api.env.smtpDisableBootVerification }}"
            - name: SMTP_HOST
              value: "{{ .Values.api.env.smtpHost }}"
            - name: SMTP_PORT
              value: "{{ .Values.api.env.smtpPort }}"
            - name: SMTP_SECURE
              value: "{{ .Values.api.env.smtpSecure }}"
            - name: SMTP_IGNORE_TLS
              value: "{{ .Values.api.env.smtpIgnoreTLS }}"
            - name: SMTP_SENDER
              value: "{{ .Values.api.env.smtpSender }}"
            - name: SENTRY_DSN
              value: "{{ .Values.api.env.sentryDsn }}"
            - name: CANCEL_TRESHOLD_IN_MIN
              value: "{{ .Values.api.env.cancelTresholdInMin }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
