apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-weblate-git-ssh-keys"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  # volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.git.pv.storage }}"
  storageClassName: "{{ .Values.git.pv.storageClassName }}"
