apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "etandem.name" . }}-pvc-{{ .Values.minio.name }}"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  # volumeMode: Block
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: "{{ .Values.minio.pv.storage }}"
  storageClassName: "{{ .Values.minio.pv.storageClassName }}"