apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.minio.name }}"
type: Opaque
data:
  MINIO_ROOT_PASSWORD: {{ .Values.minio.env.minioRootPassword | b64enc | quote }}