kind: ConfigMap
apiVersion: v1
metadata:
  name: jitsi-meet-swp
data:
{{ (.Files.Glob "files/jitsi-meet/swp/custom-config.js").AsConfig | nindent 2 }}
{{ (.Files.Glob "files/jitsi-meet/swp/custom-interface_config.js").AsConfig | nindent 2 }}