apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "etandem-weblate.fullname" . }}-secret-{{ .Values.database.name }}"
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgresPassword | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgresPassword | b64enc | quote }}