apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem-weblate.fullname" . }}-{{ .Values.redis.name }}"
  labels:
    {{- include "etandem-weblate.labels" . | nindent 4 }}
spec:
  {{- if not .Values.redis.autoscaling.enabled }}
  replicas: {{ .Values.redis.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem-weblate.name" . }}-{{ .Values.redis.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem-weblate.name" . }}-{{ .Values.redis.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem-weblate.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            - redis-server
            - --save
            - '60'
            - '1'
          ports:
            - name: direct
              containerPort: 6379
              protocol: TCP
          # readinessProbe:
          #   exec:
          #     command: ["psql", "-w", "-U", "{{ .Values.postgresUser }}", "-d", "{{ .Values.postgresDB }}", "-c", "SELECT 1"]
          #   initialDelaySeconds: 60
          #   periodSeconds: 60
          #   timeoutSeconds: 2
          # livenessProbe:
          #   exec:
          #     command: ["psql", "-w", "-U", "{{ .Values.postgresUser }}", "-d", "{{ .Values.postgresDB }}", "-c", "SELECT 1"]
          #   initialDelaySeconds: 120
          #   timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
