apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name }}-pvc-{{ .Values.webapp.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.webapp.pv.storage }}"
  storageClassName: "{{ .Values.webapp.pv.storageClassName }}"