{{- if .Values.chat.ingress.enabled -}}
{{- $svcPort := .Values.chat.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ .Values.name }}-{{ .Values.chat.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
  {{- with .Values.chat.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.chat.ingress.className }}
  {{- if .Values.chat.ingress.tls }}
  tls:
    {{- range .Values.chat.ingress.tls }}
    - hosts:
        {{- range .hosts }}        
        {{ $fqdn := printf "%s.%s" . $.Values.domain -}}
        - {{ $fqdn }}
        {{- end }}
      secretName: "{{ $.Values.name }}-tls"
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.chat.ingress.hosts }}
    {{ $fqdn := printf "%s.%s" .host $.Values.domain -}}
    - host: {{ $fqdn }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . | quote}}
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Values.name }}-{{ $.Values.chat.name }}"
                port:
                  number: {{ $svcPort }}
          {{- end }}
      {{- end }}
{{- end }}
---
{{- if .Values.chat.ingress.enabled -}}
{{- $svcWsPort := .Values.chat.service.wsPort -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: "{{ .Values.name }}-ws-{{ .Values.chat.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
  {{- with .Values.chat.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.chat.ingress.className }}
  {{- if .Values.chat.ingress.tls }}
  tls:
    {{- range .Values.chat.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        {{ $fqdn := printf "%s-ws.%s" . $.Values.domain -}}
        - {{ $fqdn }}
        {{- end }}
      secretName: "{{ $.Values.name }}-tls"
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.chat.ingress.hosts }}
    {{ $fqdn := printf "%s-ws.%s" .host $.Values.domain -}}
    - host: {{ $fqdn }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . | quote}}
            pathType: Prefix
            backend:
              service:
                name: "{{ $.Values.name }}-{{ $.Values.chat.name }}"
                port:
                  number: {{ $svcWsPort }}
          {{- end }}
      {{- end }}
{{- end }}
