apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "etandem.fullname" . }}-secret-{{ .Values.chat.name }}"
type: Opaque
stringData:
  database-url: "mongodb://{{ .Values.chat.env.mongoUser }}:{{ .Values.chat.env.mongoPassword }}@{{ include "etandem.name" . }}-mongodb-headless.{{ .Release.Namespace }}/{{ .Values.chat.env.mongoDatabase }}?authSource=admin&replicaSet=rs0"  
  redis-url: "redis://{{ include "etandem.name" . }}-redis-headless.{{ .Release.Namespace }}"  
  
  
