apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ include "etandem.fullname" . }}-{{ .Values.database.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  {{- if not .Values.database.autoscaling.enabled }}
  replicas: {{ .Values.database.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.database.name }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.database.name }}"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "etandem.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          ports:
            - name: direct
              containerPort: 5432
              protocol: TCP
          readinessProbe:
            exec:
              command: ["psql", "-w", "-U", "{{ .Values.postgresUser }}", "-d", "{{ .Values.postgresDB }}", "-c", "SELECT 1"]
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command: ["psql", "-w", "-U", "{{ .Values.postgresUser }}", "-d", "{{ .Values.postgresDB }}", "-c", "SELECT 1"]
            initialDelaySeconds: 120
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgresDB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgresUser }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresPassword }}"
            - name: PGPASSWORD
              value: "{{ .Values.postgresPassword }}"
          volumeMounts:
          - name: "configmap-{{ include "etandem.name" . }}-{{ .Values.database.name }}"
            mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: "{{ .Values.database.name }}-data"
        persistentVolumeClaim:
          claimName:  "{{ include "etandem.name" . }}-pvc-{{ .Values.database.name }}"
      - name: "configmap-{{ include "etandem.name" . }}-{{ .Values.database.name }}"
        configMap:
          name: "init-{{ include "etandem.name" . }}-{{ .Values.database.name }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
