apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "etandem.name" . }}-pvc-{{ .Values.database.name }}"
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.database.pv.storage }}"
  storageClassName: scw-bssd