apiVersion: v1
kind: Service
metadata:
  name: "{{ include "etandem.fullname" . }}-{{ .Values.database.name }}"
  labels:
    {{- include "etandem.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: direct
      protocol: TCP
      name: direct
  selector:
    app.kubernetes.io/name: "{{ include "etandem.name" . }}-{{ .Values.database.name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
